import { describe, it, expect } from 'vitest';
import { renderArtifacts, buildRenderContext, type RenderContext } from '../render';

// GitHub Actions uses ${{ }} — that's intentional. Unrendered Handlebars uses bare {{ }}.
function hasNoUnrenderedHandlebars(content: string): boolean {
  // Match {{ that is NOT preceded by $
  return !/(?<!\$)\{\{/.test(content);
}

const BASE_CONTEXT: RenderContext = buildRenderContext({
  service: {
    name: 'acme-api',
    slug: 'acme-api',
    runtime: 'NESTJS',
    port: 4000,
    healthcheckPath: '/healthz',
    replicas: 2,
    cpuMillicores: 500,
    memoryMb: 512,
    envVars: [
      { key: 'DATABASE_URL', value: 'postgresql://acme:***@postgres:5432/acme', secret: true },
      { key: 'REDIS_URL', value: 'redis://redis:6379', secret: false },
    ],
  },
  version: { version: 1, image: 'ghcr.io/acme/acme-api:v1' },
  workspace: { slug: 'acme-corp', name: 'Acme Corporation' },
});

describe('renderArtifacts', () => {
  describe('nestjs-api (polished)', () => {
    const artifacts = renderArtifacts('nestjs-api', BASE_CONTEXT);

    it('renders all 5 artifact kinds', () => {
      expect(artifacts.size).toBe(5);
      expect(artifacts.has('DOCKERFILE')).toBe(true);
      expect(artifacts.has('K8S_MANIFEST')).toBe(true);
      expect(artifacts.has('HELM_VALUES')).toBe(true);
      expect(artifacts.has('CI_PIPELINE')).toBe(true);
      expect(artifacts.has('ARGO_APP')).toBe(true);
    });

    it('generates valid Dockerfile', () => {
      const df = artifacts.get('DOCKERFILE')!;
      expect(df.filename).toBe('Dockerfile');
      expect(df.contentType).toBe('text/plain');
      expect(df.content).toContain('FROM node:22-alpine');
      expect(df.content).toContain('EXPOSE 4000');
      expect(df.content).toContain('HEALTHCHECK');
      expect(df.content).toContain('Generated by ForgeOps');
      expect(df.content).toContain('acme-api');
      expect(hasNoUnrenderedHandlebars(df.content)).toBe(true);
    });

    it('generates valid K8s deployment', () => {
      const k8s = artifacts.get('K8S_MANIFEST')!;
      expect(k8s.filename).toBe('k8s.yaml');
      expect(k8s.contentType).toBe('text/yaml');
      expect(k8s.content).toContain('kind: Deployment');
      expect(k8s.content).toContain('namespace: acme-corp');
      expect(k8s.content).toContain('image: ghcr.io/acme/acme-api:v1');
      expect(k8s.content).toContain('containerPort: 4000');
      expect(k8s.content).toContain('livenessProbe');
      expect(k8s.content).toContain('readinessProbe');
      expect(k8s.content).toContain('resources:');
      expect(hasNoUnrenderedHandlebars(k8s.content)).toBe(true);
    });

    it('generates valid Helm values', () => {
      const helm = artifacts.get('HELM_VALUES')!;
      expect(helm.filename).toBe('values.yaml');
      expect(helm.content).toContain('replicaCount: 2');
      expect(helm.content).toContain('repository: ghcr.io/acme/acme-api');
      expect(helm.content).toContain('port: 80');
      expect(helm.content).toContain('cpu: 500m');
      expect(helm.content).toContain('memory: 512Mi');
      expect(hasNoUnrenderedHandlebars(helm.content)).toBe(true);
    });

    it('generates valid CI pipeline', () => {
      const ci = artifacts.get('CI_PIPELINE')!;
      expect(ci.filename).toBe('ci.yml');
      expect(ci.content).toContain('Build and Deploy acme-api');
      expect(ci.content).toContain('actions/checkout@v4');
      expect(ci.content).toContain('docker/build-push-action@v5');
      // CI pipelines contain ${{ }} for GitHub Actions — that's expected
      expect(ci.content).toContain('${{ github.actor }}');
      expect(hasNoUnrenderedHandlebars(ci.content)).toBe(true);
    });

    it('generates valid ArgoCD application', () => {
      const argo = artifacts.get('ARGO_APP')!;
      expect(argo.filename).toBe('application.yaml');
      expect(argo.content).toContain('kind: Application');
      expect(argo.content).toContain('namespace: argocd');
      expect(argo.content).toContain('acme-corp');
      expect(argo.content).toContain('automated');
      expect(argo.content).toContain('selfHeal: true');
      expect(hasNoUnrenderedHandlebars(argo.content)).toBe(true);
    });

    it('produces deterministic output (same context = same checksum)', () => {
      const a1 = renderArtifacts('nestjs-api', BASE_CONTEXT);
      const a2 = renderArtifacts('nestjs-api', BASE_CONTEXT);
      for (const [kind, art] of a1) {
        expect(a2.get(kind)!.checksum).toBe(art.checksum);
        expect(a2.get(kind)!.content).toBe(art.content);
      }
    });

    it('computes SHA-256 checksums', () => {
      for (const [, art] of artifacts) {
        expect(art.checksum).toMatch(/^sha256:[a-f0-9]{64}$/);
      }
    });

    it('includes env vars in K8s manifest', () => {
      const k8s = artifacts.get('K8S_MANIFEST')!;
      expect(k8s.content).toContain('DATABASE_URL');
      expect(k8s.content).toContain('REDIS_URL');
    });
  });

  describe('nextjs-app (polished)', () => {
    const ctx = buildRenderContext({
      service: {
        name: 'acme-web',
        slug: 'acme-web',
        runtime: 'NEXTJS',
        port: 3000,
        healthcheckPath: '/api/health',
        replicas: 2,
        cpuMillicores: 250,
        memoryMb: 256,
        envVars: [{ key: 'NEXT_PUBLIC_API_BASE_URL', value: 'https://api.acme.dev', secret: false }],
      },
      version: { version: 1, image: 'ghcr.io/acme/acme-web:v1' },
      workspace: { slug: 'acme-corp', name: 'Acme Corporation' },
    });
    const artifacts = renderArtifacts('nextjs-app', ctx);

    it('renders all 5 artifact kinds', () => {
      expect(artifacts.size).toBe(5);
    });

    it('Dockerfile uses multi-stage build with standalone output', () => {
      const df = artifacts.get('DOCKERFILE')!;
      expect(df.content).toContain('.next/standalone');
      expect(df.content).toContain('nextjs');
      expect(df.content).toContain('EXPOSE 3000');
    });

    it('K8s manifest targets frontend namespace', () => {
      const k8s = artifacts.get('K8S_MANIFEST')!;
      expect(k8s.content).toContain('component: frontend');
      expect(k8s.content).toContain('namespace: acme-corp');
    });

    it('no unrendered Handlebars placeholders', () => {
      for (const [, art] of artifacts) {
        expect(hasNoUnrenderedHandlebars(art.content)).toBe(true);
      }
    });
  });

  describe('fastapi-service (polished)', () => {
    const ctx = buildRenderContext({
      service: {
        name: 'ml-pipeline',
        slug: 'ml-pipeline',
        runtime: 'FASTAPI',
        port: 8000,
        healthcheckPath: '/healthz',
        replicas: 2,
        cpuMillicores: 1000,
        memoryMb: 2048,
        envVars: [{ key: 'MODEL_PATH', value: '/models/classifier.onnx', secret: false }],
      },
      version: { version: 1, image: 'ghcr.io/acme/ml-pipeline:v1' },
      workspace: { slug: 'acme-corp', name: 'Acme Corporation' },
    });
    const artifacts = renderArtifacts('fastapi-service', ctx);

    it('renders all 5 artifact kinds', () => {
      expect(artifacts.size).toBe(5);
    });

    it('Dockerfile uses Python and uvicorn', () => {
      const df = artifacts.get('DOCKERFILE')!;
      expect(df.content).toContain('python:3.12-slim');
      expect(df.content).toContain('uvicorn');
      expect(df.content).toContain('EXPOSE 8000');
    });

    it('CI pipeline uses Python setup', () => {
      const ci = artifacts.get('CI_PIPELINE')!;
      expect(ci.content).toContain('actions/setup-python');
      expect(ci.content).toContain('ruff check');
    });

    it('no unrendered Handlebars placeholders', () => {
      for (const [, art] of artifacts) {
        expect(hasNoUnrenderedHandlebars(art.content)).toBe(true);
      }
    });
  });

  describe('python-worker (basic)', () => {
    const ctx = buildRenderContext({
      service: {
        name: 'event-processor',
        slug: 'event-processor',
        runtime: 'PYTHON_WORKER',
        port: 8000,
        healthcheckPath: '/healthz',
        replicas: 1,
        cpuMillicores: 250,
        memoryMb: 256,
        envVars: [{ key: 'REDIS_URL', value: 'redis://redis:6379', secret: false }],
      },
      version: { version: 1, image: 'ghcr.io/acme/event-processor:v1' },
      workspace: { slug: 'acme-corp', name: 'Acme Corporation' },
    });
    const artifacts = renderArtifacts('python-worker', ctx);

    it('renders 5 artifact kinds', () => {
      expect(artifacts.size).toBe(5);
    });

    it('no unrendered Handlebars placeholders', () => {
      for (const [, art] of artifacts) {
        expect(hasNoUnrenderedHandlebars(art.content)).toBe(true);
      }
    });
  });

  describe('go-service (basic)', () => {
    const ctx = buildRenderContext({
      service: {
        name: 'billing-api',
        slug: 'billing-api',
        runtime: 'GO_SERVICE',
        port: 8080,
        healthcheckPath: '/healthz',
        replicas: 3,
        cpuMillicores: 250,
        memoryMb: 128,
        envVars: [],
      },
      version: { version: 1, image: 'ghcr.io/acme/billing-api:v1' },
      workspace: { slug: 'acme-corp', name: 'Acme Corporation' },
    });
    const artifacts = renderArtifacts('go-service', ctx);

    it('renders 5 artifact kinds', () => {
      expect(artifacts.size).toBe(5);
    });

    it('Dockerfile uses Go and distroless', () => {
      const df = artifacts.get('DOCKERFILE')!;
      expect(df.content).toContain('golang:1.22-alpine');
      expect(df.content).toContain('distroless');
    });

    it('no unrendered Handlebars placeholders', () => {
      for (const [, art] of artifacts) {
        expect(hasNoUnrenderedHandlebars(art.content)).toBe(true);
      }
    });
  });
});
